name: Build3 oled_hijack.so

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip build-essential

    - name: Download and set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
        unzip android-ndk-r17c-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r17c
        export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin

    - name: Build oled_hijack.so
      run: |
        arm-linux-androideabi-gcc -shared -ldl -fPIC -O2 -s -D__ANDROID_API__=19 -DMENU_UNLOCK -DNET_UPDOWN -o oled_hijack.so oled_hijack_so.c

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: oled_hijack
        path: oled_hijack.so
